services:
  backend:
    image: uvindu01/coveragex-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=rootpassword
      - DATABASE_NAME=coveragexdb
      - PORT=5000
    depends_on:
      - mysql
    networks:
      - coveragex-network

  frontend:
    image: uvindu01/coveragex-frontend:latest
    container_name: frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:5000/task
    depends_on:
      - backend
    networks:
      - coveragex-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: coveragexdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coveragex-network

networks:
  coveragex-network:
    driver: bridge

volumes:
  mysql_data:
